release:
  name_template: "{{.ProjectName}} v{{.Version}}"

builds:
  -
    main: .
    id: "linux-CLI"
    binary: dose
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - 386
    ldflags:
      - -s
      - -w
  -
    main: .
    id: "win-64-CLI"
    binary: dose
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s
      - -w
  -
    main: .
    id: "win-32-CLI"
    binary: dose
    env:
      - CGO_ENABLED=1
      - CC=i686-w64-mingw32-gcc
    goos:
      - windows
    goarch:
      - 386
    ldflags:
      - -s
      - -w
archives:
  -
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
checksum:
  name_template: 'checksums.txt'

