release:
  name_template: "{{.ProjectName}} v{{.Version}}"

builds:
  -
    main: ./cmd/
    id: "gopsydose-cli"
    binary: dose
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - freebsd
      - openbsd
      - netbsd
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
      - arm
      - riscv64
    ignore:
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: arm
      - goos: openbsd
        goarch: 386
      - goos: openbsd
        goarch: arm
      - goos: netbsd
        goarch: 386
      - goos: netbsd
        goarch: arm
archives:
  -
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    files:
      - LICENSE.txt
      - README.md
      - example.alias
      - src: "cmd/gpd-names-configs/*"
        dst: gpd-names-configs
checksum:
  name_template: 'checksums.txt'

