release:
  name_template: "{{.ProjectName}} v{{.Version}}"

builds:
  -
    main: .
    id: "linux-CLI"
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - 386
archives:
  -
    rlcp: true
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    files:
      - LICENSE.txt
      - README.md
      - example.alias
      - gpd-names-configs/*
checksum:
  name_template: 'checksums.txt'

