release:
  name_template: "{{.ProjectName}} v{{.Version}}"

builds:
  -
    main: .
    id: "linux-CLI"
    binary: dose
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - 386
    ldflags:
      - -s
      - -w
  -
    main: .
    id: "linux-CLI-arm64"
    binary: dose
    env:
      - CGO_ENABLED=1
      - CC=aarch64-suse-linux-gcc-12
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s
      - -w
  -
    main: .
    id: "win-64-CLI"
    binary: dose
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s
      - -w
  -
    main: .
    id: "win-32-CLI"
    binary: dose
    env:
      - CGO_ENABLED=1
      - CC=i686-w64-mingw32-gcc
    goos:
      - windows
    goarch:
      - 386
    ldflags:
      - -s
      - -w
archives:
  -
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    files:
      - LICENSE.txt
      - README.md
      - example.alias
      - src: 'names-configs/*.toml'
        strip_parent: true
      - src: 'names-configs/replace-local-names-configs/psychonautwiki/*'
        dst: 'replace-local-names-configs/psychonautwiki'
        strip_parent: true
checksum:
  name_template: 'checksums.txt'

